### PR TITLE
Add missing parameters to EmptyLineSeparator

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by machadoit** [comment]
Hi there,

Can you please check what is wrong? Some tests are failing.

**Comment by dotdoom** [comment]
Hi, sorry about that – I still haven't set up the docker infrastructure properly to run the tests myself.  I have to (ab)use your CircleCI builds to tune the tests.  Marking as Work-in-Progress for the time being.

**Comment by machadoit** [comment]
No problem at all! Feel free to use it, just mention me when you are done, or need any help =)
Also, you can try circleCI, it's free, and then you could use it directly from your fork.

**Comment by dotdoom** [comment]
Good point, thanks!

I think it was `allowMultipleEmptyLinesInsideClassMembers` that got in the way.  It has been introduced into checkstyle very recently an might be not yet incorporated into your system.
PTAL.

**Comment by machadoit** [comment]
Thank you! 👍

**Comment by machadoit** [comment]
Your changes are live! 👍

**Pull request merged**
