### PR TITLE
Add missing parameter to ReturnCount

### PR DESCRIPTION
**Pull request by dotdoom**

### CODE REVIEW

**Comment by dotdoom** [comment]
Hate to admit it, but I've no idea why this is failing.

**Comment by rtfpessoa** [comment]
Hi @dotdoom, 

First of all thanks for your contribution. Everything looks good at first sight.

It just seems you are just missing the `src/main/resources/docs/patterns.json` entry for `ReturnCount`.

**Comment by dotdoom** [comment]
Argh, very true, thanks for the pointer.  Now I can see the error message actually does point me to check the parameters, so it's just me being blind twice.  Fixed now, PTAL?

**Comment by rtfpessoa** [comment]
LGTM :+1:

@machadoit if you do not have anything to comment, please release a new version.

**Comment by machadoit** [comment]
LGTM! 👍

**Comment by machadoit** [comment]
Hi @dotdoom,

Your PR is now live on Codacy https://www.codacy.com/account/patterns#pattern-1873

Thank you very much =)

**Comment by dotdoom** [comment]
Awesome and very prompt, thank you!

**Pull request merged**
